# Funding - Support PyPaginator
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: CybLow
# ko_fi: username
# open_collective: pypaginator
# custom: ["https://www.buymeacoffee.com/username"]
