"""Helper primitives shared by SQL search strategies."""
from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

from sqlalchemy import or_ as sa_or_
from sqlalchemy.orm.attributes import InstrumentedAttribute
from sqlalchemy.sql.elements import ColumnElement

if TYPE_CHECKING:  # pragma: no cover
    from collections.abc import Iterable, Iterator, Sequence

    from ...text.api import SqlTextNormalizer
    from ...types import SqlClause, SqlStringExpression
    from .strategies import ConditionContext


class ClauseBuilder(Protocol):
    def __call__(self, term: str, context: ConditionContext) -> SqlClause | None: ...


def matching_ids(context: ConditionContext) -> set[str]:
    """Return tokens matching the configured ID pattern.

    Args:
        context: Strategy context carrying tokens and ID pattern.

    Returns:
        A set of raw tokens considered identifiers.
    """
    return {t for t in context.tokens.raw if context.id_pattern.match(t)}


def collect_clauses(
    context: ConditionContext,
    terms: Sequence[str],
    build_clause: ClauseBuilder,
) -> list[SqlClause]:
    """Collect non-null clauses by applying a builder to all terms.

    Args:
        context: Strategy context provided to the builder.
        terms: Normalized tokens for the clause factory.
        build_clause: Callable converting a token into a SQL clause or None.

    Returns:
        List of SQL clauses, skipping None results.
    """
    return list(clause_sequences(context, terms, build_clause))


def clause_sequences(
    context: ConditionContext,
    terms: Sequence[str],
    build_clause: ClauseBuilder,
) -> Iterable[SqlClause]:
    """Yield non-null clauses generated by build_clause for each term.

    Args:
        context: Strategy context.
        terms: Tokens to process.
        build_clause: Clause builder function.

    Yields:
        SQL clauses for each term.
    """
    for term in terms:
        clause = build_clause(term, context)
        if clause is not None:
            yield clause


def phrase_clause_factory(normalizer: SqlTextNormalizer) -> ClauseBuilder:
    """Create a clause builder for phrase matching.

    Args:
        normalizer: SQL text normalizer.

    Returns:
        A ClauseBuilder function for phrases.
    """
    # Wrapper explicite plutôt que functools.partial
    def builder(term: str, context: ConditionContext) -> SqlClause | None:
        return _text_clause(normalizer, term, context, prefix=False)
    return builder


def term_clause_factory(
    normalizer: SqlTextNormalizer, ignored: set[str]
) -> ClauseBuilder:
    """Create a clause builder for term matching with ignored tokens.

    Args:
        normalizer: SQL text normalizer.
        ignored: Set of tokens to skip.

    Returns:
        A ClauseBuilder function for terms.
    """
    def builder(term: str, context: ConditionContext) -> SqlClause | None:
        if term.lower() in ignored:
            return None
        return _text_clause(normalizer, term, context, prefix=context.prefix)
    return builder


def column_attributes(
    model_class: type, fields: Sequence[str]
) -> tuple[SqlStringExpression, ...]:
    """Return typed column expressions for the provided field names.

    Args:
        model_class: ORM model class.
        fields: Field names to resolve.

    Returns:
        Tuple of column expressions.
    """
    return tuple(
        col
        for field in fields
        if (col := _column_expression(model_class, field)) is not None
    )


def match_columns(
    columns: Sequence[SqlStringExpression], tokens: set[str]
) -> SqlClause | None:
    """Build a clause matching any of the provided tokens across columns.

    Args:
        columns: Column expressions to search.
        tokens: Set of values to match.

    Returns:
        A SQL IN clause or None if no columns/tokens.
    """
    values = list(tokens)
    if not columns or not values:
        return None
    if len(columns) == 1:
        return columns[0].in_(values)
    return sa_or_(*(c.in_(values) for c in columns))  # type: ignore[arg-type]


def like_for_fields(
    normalizer: SqlTextNormalizer,
    model_class: type,
    fields: Sequence[str],
    token: str,
    *,
    prefix: bool,
) -> list[SqlClause]:
    """Return a single OR-ed LIKE clause across fields for token.

    Args:
        normalizer: SQL text normalizer.
        model_class: ORM model class.
        fields: Field names to search.
        token: Search token.
        prefix: Whether to use prefix matching.

    Returns:
        List with a single OR-ed LIKE clause.
    """
    exprs = tuple(
        normalize_fields(normalizer, model_class, fields, token, prefix=prefix)
    )
    return [sa_or_(*exprs)] if exprs else []  # type: ignore[arg-type]


def normalize_fields(
    normalizer: SqlTextNormalizer,
    model_class: type,
    fields: Sequence[str],
    token: str,
    *,
    prefix: bool,
) -> Iterable[SqlClause]:
    """Yield LIKE clauses for each field normalised with the given token.

    Args:
        normalizer: SQL text normalizer.
        model_class: ORM model class.
        fields: Field names.
        token: Search token.
        prefix: Whether to use prefix matching.

    Yields:
        LIKE clauses for each field.
    """
    return _field_clauses(normalizer, model_class, fields, token, prefix)


def _text_clause(
    normalizer: SqlTextNormalizer,
    term: str,
    context: ConditionContext,
    *,
    prefix: bool,
) -> SqlClause | None:
    """Build a LIKE clause for a term across the configured fields.

    Args:
        normalizer: SQL text normalizer.
        term: Search term.
        context: Condition context.
        prefix: Whether to use prefix matching.

    Returns:
        A LIKE clause or None.
    """
    model, fields = context.model_class, context.fields
    normalized = normalizer.normalize_text(term)
    clauses = like_for_fields(normalizer, model, fields, normalized, prefix=prefix)
    return clauses[0] if clauses else None


def _field_expression(
    normalizer: SqlTextNormalizer,
    model_class: type,
    field: str,
    token: str,
    *,
    prefix: bool,
) -> SqlClause | None:
    """Return a LIKE clause for a single field or None if unavailable.

    Args:
        normalizer: SQL text normalizer.
        model_class: ORM model class.
        field: Field name.
        token: Search token.
        prefix: Whether to use prefix matching.

    Returns:
        A LIKE clause or None.
    """
    column = _column_expression(model_class, field)
    if column is None:
        return None
    normalised = normalizer.normalize_column(column)
    pattern = f"{token}%" if prefix else f"%{token}%"
    return normalised.like(pattern, escape="/")


def _field_clauses(
    normalizer: SqlTextNormalizer,
    model_class: type,
    fields: Sequence[str],
    token: str,
    prefix: bool,
) -> Iterator[SqlClause]:
    """Yield LIKE clauses for each available field.

    Args:
        normalizer: SQL text normalizer.
        model_class: ORM model class.
        fields: Field names.
        token: Search token.
        prefix: Whether to use prefix matching.

    Yields:
        Non-null SQL clauses for the provided fields.
    """
    for field in fields:
        cl = _field_expression(normalizer, model_class, field, token, prefix=prefix)
        if cl is not None:
            yield cl


def _column_expression(model_class: type, field: str) -> SqlStringExpression | None:
    """Return a string column expression for field on model_class.

    Args:
        model_class: ORM model class.
        field: Field name.

    Returns:
        A typed string expression or None when unavailable.
    """
    try:
        attr = getattr(model_class, field)
    except AttributeError:
        return None
    if isinstance(attr, ColumnElement):
        return attr  # ColumnElement[str]
    if isinstance(attr, InstrumentedAttribute):
        clause_element = attr.__clause_element__()  # ColumnElement[str] | ColumnClause
        if isinstance(clause_element, ColumnElement):
            return clause_element
    return None


__all__ = [
    "ClauseBuilder",
    "collect_clauses",
    "clause_sequences",
    "column_attributes",
    "like_for_fields",
    "match_columns",
    "matching_ids",
    "normalize_fields",
    "phrase_clause_factory",
    "term_clause_factory",
]

