# generated by datamodel-codegen:
#   filename:  paginate.schema.json

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal, TypeAlias

Paginate: TypeAlias = Any


@dataclass
class CursorPageMeta:
    """
    Cursor page metadata (the page minus its items).
    """

    has_next: bool
    """
    Whether a following page exists.
    """
    has_previous: bool
    """
    Whether a preceding page exists.
    """
    limit: int
    """
    Page size.
    """
    next_cursor: str | None = None
    """
    Cursor to fetch the next page (null if none).
    """
    previous_cursor: str | None = None
    """
    Cursor to fetch the previous page (null if none).
    """


@dataclass
class CursorParams:
    """
    Cursor pagination parameters.
    """

    limit: int
    """
    Page size.
    """
    after: str | None = None
    """
    Opaque cursor to page forward from.
    """
    before: str | None = None
    """
    Opaque cursor to page backward from.
    """


FilterLogic: TypeAlias = Literal["and", "or"]
"""
Logical combinator for filter conditions.
"""


FilterOperator: TypeAlias = Literal[
    "eq",
    "ne",
    "gt",
    "gte",
    "lt",
    "lte",
    "in",
    "not_in",
    "contains",
    "starts_with",
    "ends_with",
    "like",
    "ilike",
    "between",
    "is_null",
    "is_not_null",
    "regex",
    "empty",
    "not_empty",
    "exists",
]
"""
One of the 20 supported filter operators (wire names).
"""


@dataclass
class FilterSpec:
    """
    A single filter condition.
    """

    field: str
    """
    Dotted field path (e.g. `user.age`).
    """
    operator: FilterOperator
    """
    Operator to apply.
    """
    value: Any
    """
    Comparison value (meaning depends on the operator).
    """
    logic: FilterLogic | None = None
    """
    AND/OR join in flat-list mode (default `and`).
    """


FuzzyMode: TypeAlias = Literal["exact", "fuzzy", "token_sort"]
"""
Fuzzy matching strategy.
"""


NullsPosition: TypeAlias = Literal["first", "last"]
"""
Null placement relative to non-null values.
"""


@dataclass
class OffsetPageMeta:
    """
    Offset page metadata (the page minus its items).
    """

    has_next: bool
    """
    Whether a following page exists.
    """
    has_previous: bool
    """
    Whether a preceding page exists.
    """
    limit: int
    """
    Page size.
    """
    page: int
    """
    The (possibly clamped) 1-based page number.
    """
    pages: int
    """
    Total number of pages.
    """
    total: int
    """
    Total matching rows across all pages.
    """


@dataclass
class OffsetParams:
    """
    Offset pagination parameters.
    """

    limit: int
    """
    Page size.
    """
    page: int
    """
    1-based page number.
    """


SearchFieldMode: TypeAlias = Literal["prefix", "contains", "exact"]
"""
How a search token matches a field value.
"""


@dataclass
class SearchSpec:
    """
    A search specification.
    """

    fields: list[str]
    """
    Fields to search (dotted paths).
    """
    query: str
    """
    Raw query string.
    """
    fuzzy: FuzzyMode | None = None
    """
    Fuzzy strategy (default `exact`).
    """
    max_results: int | None = None
    """
    Optional cap on the number of ranked results.
    """
    min_length: int | None = None
    """
    Minimum query length before searching kicks in (default 1).
    """
    mode: SearchFieldMode | None = None
    """
    Match mode (default `contains`).
    """
    threshold: int | None = None
    """
    Minimum trigram similarity, 0-100 (default 30).
    """
    weights: dict[str, Any] | None = None
    """
    Optional per-field weights (default weight 1.0).
    """


SortDirection: TypeAlias = Literal["asc", "desc"]
"""
Sort direction.
"""


@dataclass
class SortSpec:
    """
    A single sort key.
    """

    field: str
    """
    Dotted field path.
    """
    direction: SortDirection | None = None
    """
    Direction (default `asc`).
    """
    nulls: NullsPosition | None = None
    """
    Null placement (default `last`).
    """


@dataclass
class FilterGroup:
    """
    A composite AND/OR group of conditions (recursively nestable).
    """

    conditions: list[FilterNode]
    """
    Child conditions (specs or nested groups).
    """
    logic: FilterLogic
    """
    How the child conditions combine.
    """


FilterNode: TypeAlias = FilterSpec | FilterGroup
"""
A node in a nested filter tree: a leaf spec or a nested group.
"""
