import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const config: Config = {
  title: 'paginate',
  tagline:
    'Fast pagination, filtering, sorting & search — one Rust core, native Python & TypeScript packages, byte-for-byte parity',
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  // GitHub Pages: https://cyblow.github.io/paginate/
  url: 'https://cyblow.github.io',
  baseUrl: '/paginate/',
  organizationName: 'CybLow',
  projectName: 'paginate',

  onBrokenLinks: 'throw',
  markdown: {
    mermaid: true,
    hooks: {
      onBrokenMarkdownLinks: 'warn',
    },
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          sidebarPath: './sidebars.ts',
          // Docs live under /docs/ so the site root (/) can host a landing page.
          routeBasePath: '/docs',
          editUrl: 'https://github.com/CybLow/paginate/tree/main/website/',
        },
        // A library reference, not a blog.
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  // TypeScript API *reference*, generated from ts/src by TypeDoc — kept separate
  // from the usage Guides so "how to use it" and "the API surface" don't blur.
  // The Python reference is generated by pydoc-markdown (see `bun run gen:python`).
  plugins: [
    [
      'docusaurus-plugin-typedoc',
      {
        id: 'typescript-api',
        entryPoints: ['../ts/src/index.ts'],
        tsconfig: '../ts/tsconfig.json',
        out: 'docs/reference/typescript',
        readme: 'none',
        skipErrorChecking: true,
      },
    ],
  ],

  // Offline full-text search (Docusaurus ships none) — no Algolia account needed.
  // Mermaid renders the architecture / data-flow / pagination diagrams.
  themes: [
    '@docusaurus/theme-mermaid',
    [
      '@easyops-cn/docusaurus-search-local',
      {
        hashed: true,
        indexBlog: false,
        docsRouteBasePath: '/docs',
      },
    ],
  ],

  themeConfig: {
    image: 'img/social-card.png',
    colorMode: {
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'paginate',
      logo: {
        alt: 'paginate logo',
        src: 'img/logo.svg',
      },
      items: [
        {
          type: 'docSidebar',
          sidebarId: 'docsSidebar',
          position: 'left',
          label: 'Docs',
        },
        { to: '/docs/python/installation', label: 'Python', position: 'left' },
        { to: '/docs/typescript/installation', label: 'TypeScript', position: 'left' },
        { to: '/docs/rust/overview', label: 'Rust', position: 'left' },
        { to: '/playground', label: 'Playground', position: 'left' },
        { to: '/docs/reference', label: 'API', position: 'right' },
        {
          href: 'https://docs.rs/paginate-core',
          label: 'docs.rs',
          position: 'right',
        },
        {
          href: 'https://github.com/CybLow/paginate',
          label: 'GitHub',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Docs',
          items: [
            { label: 'Overview', to: '/docs/' },
            { label: 'Why paginate?', to: '/docs/general/why' },
            { label: 'Architecture', to: '/docs/general/architecture' },
            { label: 'Cross-language parity', to: '/docs/general/parity' },
          ],
        },
        {
          title: 'Languages',
          items: [
            { label: 'Python', to: '/docs/python/installation' },
            { label: 'JavaScript / TypeScript', to: '/docs/typescript/installation' },
            { label: 'Rust core', to: '/docs/rust/overview' },
          ],
        },
        {
          title: 'Packages',
          items: [
            { label: 'pypaginate (PyPI)', href: 'https://pypi.org/project/pypaginate/' },
            { label: '@cyblow/paginate (npm)', href: 'https://www.npmjs.com/package/@cyblow/paginate' },
            { label: 'paginate-core (crates.io)', href: 'https://crates.io/crates/paginate-core' },
          ],
        },
        {
          title: 'More',
          items: [
            { label: 'Rust API (docs.rs)', href: 'https://docs.rs/paginate-core' },
            { label: 'GitHub', href: 'https://github.com/CybLow/paginate' },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} CybLow. Built with Docusaurus.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['rust', 'python', 'bash', 'toml', 'json', 'typescript'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
