import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// One auto-generated sidebar from the docs/ folder tree (folders carry order +
// labels via their _category_.json). API-reference sections (TypeDoc, generated
// Python) are appended later by their plugins.
const sidebars: SidebarsConfig = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
